# Generated by Django 2.0.13 on 2019-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190310_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
